### ISSUE TITLE
Change value put in og:site_name meta to use root navigation title instead of portal site title ?

### ISSUE THREAD

**Issue by fbrun** [RedTurtle/collective.fbshare#4]
When you put data in this meta, you use the title of portal site Plone (context/@@plone_portal_state/portal_title)

is it possible for the product to use title of the root navigation of current page (context/@@plone_portal_state/navigation_root_title), to be compatible with collective.lineage for exemple, or with multilangual site (Product.LinguaPlone) instead of portal title ?

Thanks for this product...

**Comment by keul** [comment]
This was closed by https://github.com/RedTurtle/collective.fbshare/pull/5
