### ISSUE TITLE
error after installing collective.fbshare in Plone 4.3.3

### ISSUE THREAD

**Issue by rafaeltcc** [RedTurtle/collective.fbshare#6]
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/usr/local/Plone/zeocluster/parts/client2/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/Products.CMFPlone-4.3.3-py2.7.egg/Products/CMFPlone/configure.zcml", line 98.4-102.10
    ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/collective.fbshare-0.3.0-py2.7.egg/collective/fbshare/configure.zcml", line 16.2-16.32
    ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/collective.fbshare-0.3.0-py2.7.egg/collective/fbshare/browser/configure.zcml", line 38.4-39.49
    ZopeXMLConfigurationError: File "/usr/local/Plone/buildout-cache/eggs/collective.fbshare-0.3.0-py2.7.egg/collective/fbshare/browser/sc_social_like/configure.zcml", line 10.2-17.6
    ImportError: No module named plugins.facebook.browser

**Comment by keul** [comment]
@rafaeltcc I can't reproduce in any way you problem.
It seem you have sc.social.like in your buildout, but it's version not contains the `plugins.facebook.browser` submodule.

Can you provide which version of Plone and sc.social.like you are using?

**Comment by rafaeltcc** [comment]
Hio Lucca,

I was using Plone 4.3.3, I just upgraded to Plone 4.3.4, top see if it
corrected anything, but the same error remains..

The egg my buildout has downloaded is sc.social.like-1.0.1-py2.7.egg. I
think now it ignored future versions because they are still release
candidates...

Should I try one of the release candidates?

Thanks,

Rafael

**Comment by rafaeltcc** [comment]
Luca,

One more thing I forgot to mention.

I did not had sc.social.like installed when I got the error reported.

I just installed it after,  to see if it would fix the error trying to
run fb.share.

Even removing it from my buildout I still get the error trying to start
my instance.

Thanks,

Rafael

**Comment by keul** [comment]
Uh.... this version of sc.social.like is really old. Looking at the source: they don't provide the plugins submodule.
Don't be scared by the `rc` suffix, we used version 2.0 in production without any problems!

Can't fix this for both 1.0 and 2.0 branches.

**Comment by keul** [comment]
@rafaeltcc  Are you really sure? I tested it now on a fresh Plone 4.3.4 without sc.social.like and I have no error.

**Comment by rafaeltcc** [comment]
Hi Luca,

Yes. To be sure I just rerunned the buildout, commenting sc.social.like,
to be sure. Below I paste my eggs section.

eggs =
    Plone
    Pillow
    Products.BrFieldsAndWidgets
    Products.PloneFormGen
    sc.pfg.brazilianfields
    reggen.seminario
    collective.easytemplate
    collective.easyslider
    quintagroup.theme.schools
    sc.social.like
    Products.LinguaPlone
    quintagroup.plonetabs
#    collective.dancing
    Products.PloneHotfix20131210
    collective.plonetruegallery
    collective.quickupload
    quintagroup.dropdownmenu
    Products.EasyNewsletter
    quintagroup.seoptimizer >=4.0
    quintagroup.theme.sunrain
#    sc.social.like
    collective.fbshare


It spilled the same error pasted below. It is detecting a sc.social.like
even if it is not here. As a workaround I will try to install the newest
version of sc.social.like.

2015-02-05 11:09:53 INFO collective.fbshare sc.social.like found.
collective.fbshare will override Facebook OpenGraph meta
2015-02-05 11:09:53 INFO ZEO.ClientStorage zeostorage Disconnected from
storage: "('localhost', 8100)"
Traceback (most recent call last):
  File "/usr/local/Plone/zeocluster/parts/client2/bin/interpreter", line
301, in <module>
    execfile(__file__)
  File
"/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py",
line 76, in <module>
    run()
  File
"/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/run.py",
line 22, in run
    starter.prepare()
  File
"/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py",
line 86, in prepare
    self.startZope()
  File
"/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/Startup/__init__.py",
line 262, in startZope
    Zope2.startup()
  File
"/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/__init__.py",
line 47, in startup
    _startup()
  File
"/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py",
line 118, in startup
    load_zcml()
  File
"/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/startup.py",
line 52, in load_zcml
    load_site()
  File
"/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/Zope2/App/zcml.py",
line 46, in load_site
    _context = xmlconfig.file(site_zcml)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 649, in file
    include(context, name, package)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 548, in include
    processxmlfile(f, context)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 349, in
end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 359, in endElementNS
    self.context.end()
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py",
line 558, in end
    self.stack.pop().finish()
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py",
line 706, in finish
    actions = self.handler(context, **args)
  File
"/usr/local/Plone/buildout-cache/eggs/Zope2-2.13.22-py2.7.egg/OFS/metaconfigure.py",
line 46, in loadProducts
    xmlconfig.include(_context, zcml, package=product)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 548, in include
    processxmlfile(f, context)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 349, in
end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 359, in endElementNS
    self.context.end()
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py",
line 558, in end
    self.stack.pop().finish()
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py",
line 706, in finish
    actions = self.handler(context, **args)
  File
"/usr/local/Plone/buildout-cache/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/zcml.py",
line 104, in includePluginsDirective
    includeZCMLGroup(_context, info, filename)
  File
"/usr/local/Plone/buildout-cache/eggs/z3c.autoinclude-0.3.5-py2.7.egg/z3c/autoinclude/zcml.py",
line 30, in includeZCMLGroup
    include(_context, filename, includable_package)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 548, in include
    processxmlfile(f, context)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 349, in
end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 359, in endElementNS
    self.context.end()
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py",
line 558, in end
    self.stack.pop().finish()
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py",
line 706, in finish
    actions = self.handler(context, **args)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 548, in include
    processxmlfile(f, context)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 349, in
end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 359, in endElementNS
    self.context.end()
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py",
line 558, in end
    self.stack.pop().finish()
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py",
line 706, in finish
    actions = self.handler(context, **args)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 548, in include
    processxmlfile(f, context)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 380, in processxmlfile
    parser.parse(src)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 207, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 349, in
end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/xmlconfig.py",
line 359, in endElementNS
    self.context.end()
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py",
line 558, in end
    self.stack.pop().finish()
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py",
line 705, in finish
    args = toargs(context, *self.argdata)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py",
line 1397, in toargs
    args[str(name)] = field.fromUnicode(s)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/fields.py",
line 137, in fromUnicode
    value = self.context.resolve(name)
  File
"/usr/local/Plone/buildout-cache/eggs/zope.configuration-3.7.4-py2.7.egg/zope/configuration/config.py",
line 179, in resolve
    mod = __import__(mname, *_import_chickens)
  File
"/usr/local/Plone/buildout-cache/eggs/collective.fbshare-0.3.0-py2.7.egg/collective/fbshare/browser/sc_social_like/fbplugin.py",
line 4, in <module>
    from sc.social.like.plugins.facebook.browser import PluginView as
BasePluginView
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File
"/usr/local/Plone/zeocluster/parts/client2/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File
"/usr/local/Plone/buildout-cache/eggs/Products.CMFPlone-4.3.4.1-py2.7.egg/Products/CMFPlone/configure.zcml",
line 98.4-102.10
    ZopeXMLConfigurationError: File
"/usr/local/Plone/buildout-cache/eggs/collective.fbshare-0.3.0-py2.7.egg/collective/fbshare/configure.zcml",
line 16.2-16.32
    ZopeXMLConfigurationError: File
"/usr/local/Plone/buildout-cache/eggs/collective.fbshare-0.3.0-py2.7.egg/collective/fbshare/browser/configure.zcml",
line 38.4-39.49
    ZopeXMLConfigurationError: File
"/usr/local/Plone/buildout-cache/eggs/collective.fbshare-0.3.0-py2.7.egg/collective/fbshare/browser/sc_social_like/configure.zcml",
line 10.2-17.6
    ImportError: No module named plugins.facebook.browser

**Comment by keul** [comment]
Keep looking. You have "sc.social.like" two times in your .cfg :smile:

**Comment by rafaeltcc** [comment]
Luca,

Forgive my mistake. Just saw I had previously sc.social.like in another
line. Writting the email to you I saw it..

Installed newer version of it and now everything is ok... Sorry for
disturbing and congratulations on this great product.

Thanks,

Rafael

**Comment by keul** [comment]
Nop!

Thanks!
